---
name: Exercise4
on: 
  - push

jobs:
  exercise4:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        platform: ["ubuntu-24.04", "windows-2022"]
    runs-on: ${{ matrix.platform }}

    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      # Setup the specified Python version
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: echo "hello"

      - run: python --version

